import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { TwitterApi } from "twitter-api-v2";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY || "" });

const categories = ["Childhood", "Travel & Adventure", "Love & Relationships", "Lessons & Wisdom", "Career & Ambition"];
const tones = ["Honest & Reflective", "Epic & Heroic", "Romantic & Bittersweet", "Witty & Warm"];

export async function POST(req: NextRequest) {
  return handleRequest(req);
}

export async function GET(req: NextRequest) {
  return handleRequest(req);
}

async function handleRequest(req: NextRequest) {
  try {
    // 1. Verify Authorization (via query param ?secret=... or Authorization header)
    const secret = req.nextUrl.searchParams.get("secret");
    const expectedSecret = process.env.CRON_SECRET || process.env.ADMIN_PASSWORD || "chronicled2026";
    
    if (secret !== expectedSecret) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // 2. Check X API credentials
    const consumerKey = process.env.TWITTER_CONSUMER_KEY;
    const consumerSecret = process.env.TWITTER_CONSUMER_SECRET;
    const accessToken = process.env.TWITTER_ACCESS_TOKEN;
    const accessSecret = process.env.TWITTER_ACCESS_SECRET;

    if (!consumerKey || !consumerSecret || !accessToken || !accessSecret) {
      return NextResponse.json({ error: "Missing Twitter API credentials in environment" }, { status: 500 });
    }

    const twitterClient = new TwitterApi({
      appKey: consumerKey,
      appSecret: consumerSecret,
      accessToken: accessToken,
      accessSecret: accessSecret,
    });

    // 3. Choose random category and tone
    const category = categories[Math.floor(Math.random() * categories.length)];
    const tone = tones[Math.floor(Math.random() * tones.length)];

    // 4. Generate prompts via Claude
    const systemPrompt = `You are a master biographer and creative director. You write viral, highly engaging, thought-provoking writing prompts for people to reflect on their lives, memories, and family histories.
Your goal is to get people to think about their personal story and realize it's worth turning into a printed or digital memoir.

Your writing style is heavily optimized for X/Twitter virality:
- Every prompt must start with a short, scroll-stopping question or hook.
- Write in short, single-sentence paragraphs.
- Keep the tone emotional, deep, slightly dramatic, and literary.
- Return your output as a clean JSON array of exactly 5 prompts.
- Do not output any markdown or explanation, return ONLY the raw JSON array.

JSON Format:
[
  {
    "id": 1,
    "hook": "First scroll-stopping line",
    "body": "Secondary sentence expanding the theme",
    "takeaway": "Bookmarkable summary sentence"
  }
]`;

    const userPrompt = `Generate exactly 5 viral writing prompts about:
Category: "${category}"
Literary Tone: "${tone}"

Ensure the output is a valid JSON array matching the requested schema. Return nothing else.`;

    const message = await anthropic.messages.create({
      model: "claude-opus-4-5",
      max_tokens: 1000,
      system: systemPrompt,
      messages: [{ role: "user", content: userPrompt }],
    });

    const responseText = message.content[0].type === "text" ? message.content[0].text.trim() : "";
    const jsonString = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
    const prompts = JSON.parse(jsonString);

    if (!prompts || prompts.length === 0) {
      throw new Error("No prompts generated by AI");
    }

    // 5. Select the first prompt and format the tweet
    const selected = prompts[0];
    const tweetText = `"${selected.hook}"\n\n${selected.body}\n\n${selected.takeaway}\n\n📖 Write yours at: getchronicled.art`;

    // 6. Ensure character limit is respected
    if (tweetText.length > 280) {
      console.warn("Generated tweet is too long, shortening...");
      // Fallback to simpler format if it exceeds 280 chars
      const fallbackText = `"${selected.hook}"\n\n${selected.takeaway}\n\n📖 getchronicled.art`;
      if (fallbackText.length > 280) {
        throw new Error("Prompt draft exceeded 280 characters even in fallback mode.");
      }
      
      console.log("Posting fallback tweet...");
      const tweetResponse = await twitterClient.v2.tweet(fallbackText);
      return NextResponse.json({ success: true, posted: "fallback", data: tweetResponse.data });
    }

    // 7. Post to X
    console.log("Posting generated tweet...");
    const tweetResponse = await twitterClient.v2.tweet(tweetText);

    return NextResponse.json({
      success: true,
      category,
      tone,
      tweetText,
      data: tweetResponse.data,
    });
  } catch (err: any) {
    console.error("Cron Twitter post error:", err);
    return NextResponse.json({ error: err.message || "Failed to post daily tweet" }, { status: 500 });
  }
}
